[package]
name = "nbody"
version = "0.1.0"
authors = ["magu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = '0.6'
rand = '0.7'
glam = { version = "0.18.0", features = ["mint"] } 